FROM docker.io/library/ubuntu:22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
        # Build
        cmake ninja-build g++ git \
        # Basalt
        libtbb-dev libeigen3-dev libopencv-dev libfmt-dev \
        libboost-serialization-dev libboost-date-time-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev \
        # Pangolin
        libglew-dev \
        # Rosbag
        libbz2-dev liblz4-dev \
        # Development
        clang-format

RUN useradd -m -s /bin/bash basalt && \
    chown -R basalt:basalt /home/basalt
